apiVersion: v1
kind: Service
metadata:
  name: {{ include "mio-gateway.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mio-gateway.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "mio-gateway.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
    - name: metrics
      port: {{ .Values.service.metricsPort }}
      targetPort: {{ .Values.service.metricsPort }}
      protocol: TCP
