{{- if .Values.nats.promExporter.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "mio-nats.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mio-nats.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: nats
      app.kubernetes.io/instance: {{ .Release.Name }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  endpoints:
    - port: monitor
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
{{- end }}
