// Package main implements the channel-type code generator.
//
// Reads proto/channels.yaml and emits:
//   - sdk-go/channeltypes.go  (Go: var Known map[string]bool)
//   - sdk-py/mio/channeltypes.py (Python: KNOWN set[str])
//
// Only channels with status: active are emitted to Known/KNOWN.
// Deprecated aliases are available via Aliases (Go) / ALIASES (Python).
//
// Usage: go run ./tools/genchanneltypes/ [repo-root]
// Wired into `make proto-gen`. CI runs `git diff --exit-code` on outputs.
package main

import (
	"fmt"
	"log"
	"os"
	"path/filepath"
	"runtime"
	"sort"
	"strings"
	"text/template"
	"time"

	"gopkg.in/yaml.v3"
)

// channelEntry mirrors one entry in channels.yaml channel_types list.
type channelEntry struct {
	Name   string `yaml:"name"`
	Status string `yaml:"status"`
}

// channelsFile mirrors the top-level structure of channels.yaml.
type channelsFile struct {
	ChannelTypes      []channelEntry    `yaml:"channel_types"`
	DeprecatedAliases map[string]string `yaml:"deprecated_aliases"`
}

// repoRoot returns the absolute path to the repository root.
// Falls back to the directory two levels above this file if called via `go run`.
func repoRoot() string {
	// When invoked via `go run`, runtime.Caller gives the source path.
	_, file, _, ok := runtime.Caller(0)
	if !ok {
		// Fallback: use cwd.
		wd, _ := os.Getwd()
		return wd
	}
	// tools/genchanneltypes/main.go → ../../ = repo root
	return filepath.Clean(filepath.Join(filepath.Dir(file), "..", ".."))
}

const goTemplate = `// Code generated by tools/genchanneltypes. DO NOT EDIT.
// Source: proto/channels.yaml
// Generated: {{ .Timestamp }}
//
// Known contains every channel_type with status: active.
// Add new channels to proto/channels.yaml; re-run: make proto-gen.
// Do NOT add account_id / tenant_id / conversation_id as labels — see metrics.go.
package sdk

// Known is the set of active channel_type strings from proto/channels.yaml.
// SDK publish calls reject any channel_type not present here.
//
// Asymmetry note (publish-only validation):
//   Publish: SDK rejects channel_type not in Known.
//   Consume: SDK passes through — consumers must tolerate forward-compatible values.
var Known = map[string]bool{
{{- range .Active }}
	"{{ . }}": true,
{{- end }}
}

// Aliases maps deprecated channel_type slug → current slug.
// The SDK accepts both the alias and the current name during migration windows.
var Aliases = map[string]string{
{{- range $k, $v := .Aliases }}
	"{{ $k }}": "{{ $v }}",
{{- end }}
}
`

const pyTemplate = `# Code generated by tools/genchanneltypes. DO NOT EDIT.
# Source: proto/channels.yaml
# Generated: {{ .Timestamp }}
#
# KNOWN contains every channel_type with status: active.
# Add new channels to proto/channels.yaml; re-run: make proto-gen.
# Do NOT add account_id / tenant_id / conversation_id as metric labels — cardinality bomb.

# KNOWN is the set of active channel_type strings from proto/channels.yaml.
# SDK publish calls reject any channel_type not present here.
#
# Asymmetry note (publish-only validation):
#   Publish: SDK rejects channel_type not in KNOWN.
#   Consume: SDK passes through — consumers must tolerate forward-compatible values.
KNOWN: set[str] = {
{{- range .Active }}
    "{{ . }}",
{{- end }}
}

# ALIASES maps deprecated channel_type slug -> current slug.
ALIASES: dict[str, str] = {
{{- range $k, $v := .Aliases }}
    "{{ $k }}": "{{ $v }}",
{{- end }}
}
`

type templateData struct {
	Timestamp string
	Active    []string
	Aliases   map[string]string
}

func main() {
	root := repoRoot()
	if len(os.Args) > 1 {
		root = os.Args[1]
	}

	// Read channels.yaml.
	yamlPath := filepath.Join(root, "proto", "channels.yaml")
	raw, err := os.ReadFile(yamlPath)
	if err != nil {
		log.Fatalf("cannot read %s: %v", yamlPath, err)
	}

	var cf channelsFile
	if err := yaml.Unmarshal(raw, &cf); err != nil {
		log.Fatalf("cannot parse %s: %v", yamlPath, err)
	}

	// Collect active channel types.
	var active []string
	for _, ct := range cf.ChannelTypes {
		if strings.ToLower(ct.Status) == "active" {
			active = append(active, ct.Name)
		}
	}
	sort.Strings(active)

	aliases := cf.DeprecatedAliases
	if aliases == nil {
		aliases = make(map[string]string)
	}

	data := templateData{
		Timestamp: time.Now().UTC().Format(time.RFC3339),
		Active:    active,
		Aliases:   aliases,
	}

	// Emit Go file.
	goOut := filepath.Join(root, "sdk-go", "channeltypes.go")
	if err := renderTemplate("go", goTemplate, data, goOut); err != nil {
		log.Fatalf("emit Go: %v", err)
	}
	fmt.Printf("written: %s\n", goOut)

	// Emit Python file.
	pyOut := filepath.Join(root, "sdk-py", "mio", "channeltypes.py")
	if err := renderTemplate("py", pyTemplate, data, pyOut); err != nil {
		log.Fatalf("emit Python: %v", err)
	}
	fmt.Printf("written: %s\n", pyOut)
}

func renderTemplate(name, tmplText string, data templateData, outPath string) error {
	tmpl, err := template.New(name).Parse(tmplText)
	if err != nil {
		return fmt.Errorf("parse template: %w", err)
	}

	f, err := os.Create(outPath)
	if err != nil {
		return fmt.Errorf("create %s: %w", outPath, err)
	}
	defer f.Close()

	return tmpl.Execute(f, data)
}
