// Code generated by tools/genchanneltypes. DO NOT EDIT.
// Source: proto/channels.yaml
// Generated: 2026-05-08T06:06:28Z
//
// Known contains every channel_type with status: active.
// Add new channels to proto/channels.yaml; re-run: make proto-gen.
// Do NOT add account_id / tenant_id / conversation_id as labels — see metrics.go.
package sdk

// Known is the set of active channel_type strings from proto/channels.yaml.
// SDK publish calls reject any channel_type not present here.
//
// Asymmetry note (publish-only validation):
//   Publish: SDK rejects channel_type not in Known.
//   Consume: SDK passes through — consumers must tolerate forward-compatible values.
var Known = map[string]bool{
	"zoho_cliq": true,
}

// Aliases maps deprecated channel_type slug → current slug.
// The SDK accepts both the alias and the current name during migration windows.
var Aliases = map[string]string{
}
