{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "mio-echo-consumer.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mio-echo-consumer.labels" . | nindent 4 }}
automountServiceAccountToken: false
{{- end }}
